AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-calculator 

  Sample SAM Template for a serverless calculator application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SamCalculatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # here is path to lambda function in calculator.py
      CodeUri: .
      # This is where function is in the file
      Handler: calculator.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        # here are the api paths
        CalculatorAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /calculate
            # sending data so this would be a post, not a get
            Method: POST
